#ifndef CONFIG_H
#define CONFIG_H

#define HOME_DIR ""
#define MAX_THREADS
#define DATABASE_NAME

#define INSTANCE_FILE_DATA_DIR
#define USER_FILE_DATA_DIR

#define USERDAT_TABLE_NAME
#define USERDAT_DAT_COL_ID
#define USERDAT_ALGO_COL_ID
#define USERDAT_DAT_PRIORITY_COL_ID
#define USERDAT_DATA_DIR_PATH

#define INSTANCE_TABLE_NAME
#define INSTANCE_DAT_COL_ID
#define INSTANCE_PRIO_COL_ID

#define DB_POLL_THREAD_SLEEP_TIMER 2

#define WORKER_QUEUE_SIZE
#endif